//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Managment_Data_Access_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_Hospital_ManagmentEntities : DbContext
    {
        public Db_Hospital_ManagmentEntities()
            : base("name=Db_Hospital_ManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_department_information> m_department_information { get; set; }
        public virtual DbSet<m_designation_information> m_designation_information { get; set; }
        public virtual DbSet<m_employee_information> m_employee_information { get; set; }
        public virtual DbSet<a_m_lookup_hedar> a_m_lookup_hedar { get; set; }
        public virtual DbSet<a_m_lookup_line> a_m_lookup_line { get; set; }
        public virtual DbSet<m_user_Login_information> m_user_Login_information { get; set; }
        public virtual DbSet<m_hospital_information> m_hospital_information { get; set; }
        public virtual DbSet<m_material_type_infromation> m_material_type_infromation { get; set; }
        public virtual DbSet<m_unit_information> m_unit_information { get; set; }
        public virtual DbSet<m_item_information> m_item_information { get; set; }
    }
}
