//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Managment_Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_department_information
    {
        public long department_id { get; set; }
        public Nullable<System.DateTime> department_start_date { get; set; }
        public string department_code { get; set; }
        public string department_name { get; set; }
        public string deparment_address { get; set; }
        public string deparment_description { get; set; }
        public Nullable<long> hospital_id { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
