//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Managment_Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_employee_information
    {
        public int employee_id { get; set; }
        public string employee_code { get; set; }
        public Nullable<int> employee_title { get; set; }
        public Nullable<int> employee_gender { get; set; }
        public string employee_name { get; set; }
        public int employye_designation { get; set; }
        public int employee_department { get; set; }
        public Nullable<System.DateTime> employee_dob { get; set; }
        public Nullable<System.DateTime> employee_joing_date { get; set; }
        public string employee_Address { get; set; }
        public string employee_Address1 { get; set; }
        public string employee_city { get; set; }
        public string employee_pan { get; set; }
        public string employee_adharchard { get; set; }
        public string employee_alternet_no { get; set; }
        public string employee_mobile { get; set; }
        public string employee_email_id { get; set; }
        public Nullable<int> employee_bank_name { get; set; }
        public string employee_account_no { get; set; }
        public string employee_ifsc_code { get; set; }
        public Nullable<int> employee_branch { get; set; }
        public string employee_photo { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public string attr1 { get; set; }
        public string attr2 { get; set; }
        public string attr3 { get; set; }
        public Nullable<int> attr4 { get; set; }
    }
}
