//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Managment_Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_hospital_information
    {
        public int hospital_id { get; set; }
        public string hospital_name { get; set; }
        public string hospital_address { get; set; }
        public string hospital_email_address { get; set; }
        public byte[] logo { get; set; }
        public string hospital_city { get; set; }
        public string hospital_pan { get; set; }
        public string hospital_gst_number { get; set; }
        public string hospital_contact_number { get; set; }
        public string hospital_contact_number1 { get; set; }
        public string hospital_web_site { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
